name: Release Editor Kit

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use for editor-preload-ecosystem package'
        required: true
      use_npm:
        description: 'Use npm packages instead of building from source'
        type: boolean
        default: false
      build_official:
        description: 'Also build and publish official preload package'
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=22.6.0'
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/build-editor-preload.js
          chmod +x ./scripts/build-official-preload.js

      - name: Build editor-preload packages
        run: |
          USE_NPM_ARG=""
          if [ "${{ github.event.inputs.use_npm }}" == "true" ]; then
            USE_NPM_ARG="--use-npm"
          fi
          
          BUILD_OFFICIAL_ARG=""
          if [ "${{ github.event.inputs.build_official }}" == "true" ]; then
            BUILD_OFFICIAL_ARG="--build-official"
          fi
          
          ./scripts/build-editor-preload.js --version=${{ github.event.inputs.version }} $USE_NPM_ARG $BUILD_OFFICIAL_ARG

      - name: Prepare packages list for publishing
        id: prepare-packages
        run: |
          PACKAGES="editor-preload-ecosystem"
          if [ "${{ github.event.inputs.build_official }}" == "true" ]; then
            PACKAGES="editor-preload-official\neditor-preload-ecosystem"
          fi
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

      - name: Release packages and Sync to CDN
        uses: galacean/publish@main
        with:
          publish: false
          packages: ${{ steps.prepare-packages.outputs.packages }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
          OASISBE_UPLOAD_URL: https://oasisbe.alipay.com/api/file/no-auth/crypto/upload
          OASISBE_REQUEST_HEADER: ${{secrets.OASISBE_REQUEST_HEADER}}
          OASISBE_PUBLIC_KEY: ${{secrets.OASISBE_PUBLIC_KEY}}
          
      - name: Prepare artifact paths
        id: prepare-artifacts
        run: |
          PATHS="editor-preload-ecosystem/dist/browser.js"
          if [ "${{ github.event.inputs.build_official }}" == "true" ]; then
            PATHS="editor-preload-official/dist/browser.js\neditor-preload-ecosystem/dist/browser.js"
          fi
          echo "paths<<EOF" >> $GITHUB_OUTPUT
          echo "$PATHS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: editor-preload-packages
          path: ${{ steps.prepare-artifacts.outputs.paths }}
          retention-days: 7
